skadogg/personal-tv-guide

modules/shield.py, out.html
Added <a href> tag to shield function
=> Fixes #1 - Badges should link back to JustWatch pages

build_html.py, modules/genre.py, modules/html.py, scrape_movies.py, scrape_tv.py
Fixed file paths to relative, instead of using full paths. 
[ISSUE](https://github.com/skadogg/personal-tv-guide/issues/9)
=> changed file paths to relative paths

auto_sign_in.py, scrape_movies.py, scrape_tv.py
Added automated login with Selenium. Google OAuth is slightly unpredictable, because it can put up captcha checks sometimes (and doesn't sometimes as well...).
So I hard-coded in a login for a dummy test account which can be used endlessly. I don't see a point of storing it very securely, since the email is from '10 Minute Mail', but I can look into that if you'd like :)
https://github.com/skadogg/personal-tv-guide/issues/2
=> Automate selenium login

scrape_movies.py, scrape_tv.py
=> Scrolling misses a page

.gitignore, README.md, modules/auto_sign_in.py, scrape_movies.py, scrape_tv.py
=> Fixes #21 - Implement new autologin for scraping

scrape_movies.py, scrape_tv.py
- Fixes #22
- Adds dev_mode flag to pull less data for quicker development
=> Fixes #22 - Python progress bars while scraping?

.env-sample, .gitignore, build_html.py, modules/genre.py, scrape_movies.py, scrape_tv.py
As requested in issue #26, I've extracted the variables into a dedicated .env file. This task was accomplished using the [python-dotenv](https://pypi.org/project/python-dotenv/) library, which facilitates the loading of variables from a .env file. 
Furthermore, to assist users, a sample file for the .env configuration has been included.
Let me know if there are any additional adjustments needed 😀
=> Issue #26 - Extract variables to env file

modules/justwatch.py, scrape_movies.py, scrape_tv.py
=> ♻ Creates new module & function to get number of titles from page instead of hardcoding

README.md
=> 📝 Adds explanation of .env with nice, little table in readme file

css/disability-pride-flag.css
=> ♿ Create stylesheet for visual impairment

README.md
=> 📝 Updates readme with instructions for installing required modules

build_html.py, modules/html.py, modules/justwatch.py
=> 🚸 Balance movie and TV runtime in final output

modules/html.py
=> 🐛 Rows printing past the end time

modules/auto_sign_in.py, modules/data_bin_convert.py, modules/genre.py, modules/html.py, modules/justwatch.py, modules/runtime.py, run.py
=> 🔊 Adds a whole bunch of logging

modules/auto_sign_in.py, scrape_movies.py, scrape_tv.py
Temporary patch until we can deal with #79
=> 🚑 Turns off headless to prompt for privacy acknowledgement

modules/auto_sign_in.py
=> 🚑 Waits a few seconds before clicking

modules/justwatch.py
=> ⚡ Adjusts method for scrolling by reading page height

css/nord.css, modules/html.py
=> 🚸 Reads ld-json data to get image URL

modules/justwatch.py
=> 🐛 Resets connection every so often to avoid locking up

classes/activity.py, modules/data_bin_convert.py, modules/justwatch.py
This Fixes #94 
In `modules > data_bin_convert.py > bin_to_data` added try/except.
So if it doesn't find .bin file it will return empty list.
=> Added try/except to modules > data_bin_convert.py > bin_to_data()

modules/justwatch.py
=> 🗃️ Updates TV show episode info in existing data

run.py
This fixes #105 
Add encoding while opening file for handling special characters.
=> Update run.py, Add encoding while opening output html file

modules/justwatch.py, modules/runtime.py, run.py
=> 🔀 Skadogg/issue101

README.md
=> 📝 Updates readme with more organized structure

modules/justwatch.py, run.py
=> 🚛 Removes shows from main database when no longer in watchlists

README.md
Changed Project Title -> **Personal TV Guide**
Resolves #109
=> Project Title -> **Personal TV Guide** in README.md

modules/auto_sign_in.py, modules/justwatch.py
=> 👽 Renames and disables click_through_privacy_modal
